# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "vmd" "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/93c7379e-5f08-46ac-a1ef-b5dc8f99ac8f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/7309-F28D";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
  
  fileSystems."/mnt/1TB_HDD" =
    { device = "/dev/disk/by-uuid/5418574A185729EE";
      fsType = "ntfs3";
      options = [ "nofail" "force" "uid=1000" "gid=100" "dmask=007" "fmask=117" ];
    };

  fileSystems."/mnt/3TB_HDD" =
    { device = "/dev/disk/by-uuid/B070C07270C040B8";
      fsType = "ntfs3";
      options = [ "nofail" "uid=1000" "gid=100" "dmask=007" "fmask=117" ];
    };

  swapDevices = [
     { device = "/swapfile"; size = 20 * 1024; } # 10GB
  ];

  environment.systemPackages = with pkgs; [
    ntfs3g
  ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
